name: truffleruby-bundler

on:
  pull_request:

  push:
    branches:
      - master

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

defaults:
  run:
    shell: bash

jobs:
  truffleruby_bundler:
    name: Bundler (Truffleruby)
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup ruby
        uses: ruby/setup-ruby@360dc864d5da99d54fcb8e9148c14a84b90d3e88 # v1.165.1
        with:
          ruby-version: truffleruby-23.1.1
          bundler: none
      - name: Prepare dependencies
        run: |
          bin/rake spec:parallel_deps
      - name: Run Test
        run: |
          bin/parallel_rspec --tag truffleruby_only --tag truffleruby
        working-directory: ./bundler
    timeout-minutes: 20
