name: windows-bundler

on:
  pull_request:

  push:
    branches:
      - master
      - 3.3

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  windows_bundler:
    name: Bundler on Windows (${{ matrix.ruby.name }})

    runs-on: windows-2022

    env:
      RGV: ..

    strategy:
      fail-fast: false
      matrix:
        ruby:
          - { name: jruby-9.3, value: jruby-9.3.4.0 }
          - { name: ruby-2.7, value: 2.7.6 }
          - { name: ruby-3.0, value: 3.0.4 }
          - { name: ruby-3.1, value: 3.1.2 }

    steps:
      - uses: actions/checkout@v3
      # set JDK version, see https://github.com/actions/runner-images
      - run: echo JAVA_HOME=$env:JAVA_HOME_17_X64 >> $env:GITHUB_ENV
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby.value }}
          bundler: none
      - name: Install dependencies
        run: |
          bin/rake spec:parallel_deps
        working-directory: ./bundler
        shell: bash
      - name: Run specs
        run: |
          bin/parallel_rspec
        working-directory: ./bundler
        shell: bash
        if: "!startsWith(matrix.ruby.name, 'jruby')"
