name: windows

on: [push]

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        ruby: [ '2.4.x', '2.5.x', '2.6.x' ]
    steps:
      - uses: actions/checkout@master
      - run: git submodule update -i
      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: DevKit, ENV['PATH']
        uses: MSP-Greg/msys2-action@master
      - name: Install Dependencies
        run: gem --% install "rake:>=12.0.0" "minitest:>=5.10.1" --conservative --no-document
      - name: Run Test
        run: |
          New-Item -Path "C:\git" -ItemType Junction -Value "C:\Program Files\Git" 1> $null
          $env:GIT = "C:\git\cmd\git.exe"
          rake test
    timeout-minutes: 15
